const ErrorCodes = {
    DATA_UNAVAILABLE: 'DATA_UNAVAILABLE',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    EXPIRED_VALIDATION_CODE: 'EXPIRED_VALIDATION_CODE',
    USER_ENTRY_NOT_FOUND: 'USER_ENTRY_NOT_FOUND',
};

module.exports = ErrorCodes;